/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32l07xx.h"
#include "stm32l07xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	GPIO_Handle_t GPIO_Led, GPIO_Button;
	memset(&GPIO_Led, 0x00, sizeof(GPIO_Led));
	memset(&GPIO_Button, 0x00, sizeof(GPIO_Button));

	GPIO_Led.pGPIOx = GPIOA;
	GPIO_Led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
	GPIO_Led.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	GPIO_Led.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_Led.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_Led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIO_Led.pGPIOx, ENABLE);

	GPIO_Init(&GPIO_Led);

	GPIO_Button.pGPIOx = GPIOC;
	GPIO_Button.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	GPIO_Button.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	GPIO_Button.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_Button.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PU; /* Because there is a pull up resistor on the board */

	GPIO_PeriClockControl(GPIO_Button.pGPIOx, ENABLE);

	GPIO_Init(&GPIO_Button);

	/*
	 * 	IRQ Configuration
	 * */
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI4_15, 15);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI4_15, ENABLE);

	while(1);

	return 0;
}

void EXTI4_15_IRQHandler(void) {
	GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_5);
	GPIO_IRQHandling(GPIO_PIN_13);
}
